# Generated by ChatGPT for affiliate-only refactor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_icon_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="affiliate_url",
            field=models.URLField(blank=True, help_text="Partner/Affiliate Link (Weiterleitung)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_eur",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="ProductKey",
        ),
    ]
